CREATE TABLE orders (id TEXT PRIMARY KEY, data TEXT NOT NULL, nome TEXT, cognome TEXT, telefono TEXT, q1 INTEGER DEFAULT 0, q6 INTEGER DEFAULT 0, uova INTEGER DEFAULT 0, euro REAL DEFAULT 0, note TEXT, pagato INTEGER DEFAULT 0, consegnato INTEGER DEFAULT 0, data_pag TEXT DEFAULT '', metodo TEXT DEFAULT '', per_il TEXT DEFAULT '', stato TEXT DEFAULT 'ok', ricordato INTEGER DEFAULT 0);
CREATE TABLE loads (id TEXT PRIMARY KEY, data TEXT NOT NULL, uova INTEGER NOT NULL, utente TEXT, note TEXT, ins TEXT);
CREATE TABLE costs (id TEXT PRIMARY KEY, data TEXT NOT NULL, descr TEXT, euro REAL NOT NULL, utente TEXT, ins TEXT, qta REAL DEFAULT 0, unita TEXT DEFAULT '');
CREATE TABLE hens (id TEXT PRIMARY KEY, data TEXT NOT NULL, tot INTEGER, prod INTEGER, utente TEXT, note TEXT, ins TEXT);
CREATE TABLE users (tk TEXT PRIMARY KEY, nome TEXT NOT NULL, ruolo TEXT NOT NULL, creato TEXT);
CREATE TABLE settings (k TEXT PRIMARY KEY, v TEXT);
CREATE TABLE idem (rid TEXT PRIMARY KEY, res TEXT, ts INTEGER);
CREATE TABLE contacts (id TEXT PRIMARY KEY, nome TEXT NOT NULL, tel TEXT NOT NULL);
